name: Build Executables

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python-version: 3.9
            artifact-name: long-to-short-gui-linux

          - os: windows-latest
            python-version: 3.9
            artifact-name: long-to-short-gui-windows

          - os: macos-latest
            python-version: 3.9
            artifact-name: long-to-short-gui-macos

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Build standalone executable
        run: |
          pip3 install pyinstaller
          pyinstaller --onefile --noconsole gui.py

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.artifact-name }}
          path: |
            dist/gui
